package server.replica;

public enum RequestType {
    OBTAIN_COINS, TRANSFER, CLIENT_AMOUNT, GET, GET_ALL, GET_HASHED, 
    MINE, GET_LAST_BLOCK, GET_NOT_MINED, INSTALL_SMART_CONTRACT, SMART_CONTRACT;
}